---
- hosts: localhost
  tasks:

  - name: Pull in the swap variables
    include_vars: digital_ocean.env

#  - name: Create a domain record 
#    digital_ocean_domain:
#      api_token: "{{ DO_API_KEY }}"
#      state: present
#      name: teamspeak.kidsoncomputers.work

  - name: Create Droplet
    digital_ocean:
      state: present
      command: droplet
      name: teamspeak
      api_token: "{{ DO_API_KEY }}"
      size_id: "{{ SIZE | default('512mb') }}"
      region_id: "{{ REGION_ID | default('nyc2') }}"
      image_id: "{{ IMAGE | default(14238961) }}"
      wait_timeout: 500
      unique_name: yes
      ssh_key_ids: "{{ SSH_KEYS }}"
    register: my_droplet
  - debug: msg="ID is {{ my_droplet.droplet.id }}"
  - debug: msg="IP is {{ my_droplet.droplet.ip_address }}"
  
  - name: Register droplet to domain
    digital_ocean_domain:
      api_token: "{{ DO_API_KEY }}"
      state: present
      name: "{{ my_droplet.droplet.name }}.kidsoncomputers.work"
      ip: "{{ my_droplet.droplet.ip_address }}"
#      id: "{{ my_droplet.droplet.id }}"

  - name: Add teamspeak host to the hosts file
    lineinfile:
      dest: "{{ inventory_file }}"
      regexp: '^teamspeak*' 
      line: "teamspeak ansible_user=root ansible_host={{ my_droplet.droplet.ip_address }}"
